[package]
name = "league-toolkit"
version = "0.1.0"
edition = "2018"
authors = ["crauzer"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1.1"
num_enum = "0.5.4"
thiserror = "1.0.30"
